#!/bin/bash
folderName=$1
archiveName=$2
mkdir $folderName &> /dev/null
for extension in "$@"
do
	find ~ -name *.$extension -exec cp -prv '{}' $folderName/ ';' &> /dev/null
done
cd $folderName
cd ..
tar -zcf $archiveName.tar.gz $folderName &> /dev/null
echo done